services:
  dash:
    image: glanceapp/glance
    expose:
      - 8080
    environment:
      - MINIFLUX_TOKEN=${MINIFLUX_TOKEN}
      - MINIFLUX_API_URL=${MINIFLUX_URL}
      - MINIFLUX_LINKS_URL=${MINIFLUX_URL}
    volumes:
      - /home/tyler/apps/glance:/app/config
    restart: unless-stopped

networks:
  cluster:
    external: true
