services:
  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - ${VALKEY_DATA_DIR}:/data

  search:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    expose:
      - 8080
    volumes:
      - ${CONFIG_DIR}:/etc/searxng:rw
      - ${DATA_DIR}:/var/cache/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARCH_HOSTNAME:-localhost}/

networks:
  cluster:
    external: true
  searxng:
