services:
  app:
    image: "portainer/portainer-ce:${PORTAINER_VERSION:-lts}"
    volumes:
      - /home/tyler/apps/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cluster
    deploy:
      placement:
        constraints:
          - node.hostname == coconut

networks:
  cluster:
    external: true

