services:
  media:
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - "${CONFIG_DIR}:/config"
      - "${MOVIE_DIR}:/data/movies"
      - "${SHOW_DIR}:/data/tvshows"
      - "${MUSIC_DIR}:/data/music"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
    name: private
